export const specialtyData = [
  { name: "Bipolar" },
  { name: "LGBTQ" },
  { name: "Medication/Prescribing" },
  { name: "Suicide History/Attempts" },
  { name: "General Mental Health" },
  { name: "Men's Issues" },
  { name: "Relationship Issues" },
  { name: "Trauma & PTSD" },
  { name: "Personality Disorders" },
  { name: "Personal Growth" },
  { name: "Substance Use/Abuse" },
  { name: "Pediatrics" },
  { name: "Women's Issues" },
  { name: "Chronic Pain" },
  { name: "Weight Loss & Nutrition" },
  { name: "Eating Disorders" },
  { name: "Diabetic Diet and Nutrition" },
  { name: "Coaching" },
  { name: "Life Coaching" },
  { name: "Obsessive-Compulsive Disorders" },
  { name: "Neuropsychological Evaluations & Testing" },
  { name: "Attention and Hyperactivity (ADHD)" },
  { name: "Sleep Issues" },
  { name: "Schizophrenia and Psychotic Disorders" },
  { name: "Learning Disorders" },
  { name: "Domestic Abuse" }
]; 